### ISSUE TITLE
No description on Pypi

### ISSUE THREAD

**Issue by andy-maier** [justin8/convert_videos#4]
This project is available as a package on Pypi (https://pypi.org/project/convert-videos), but there is no description for it on Pypi, nor a link back to this repo here.

It would be good to have a description on Pypi (e.g. the README.md file of this repo here), and a link back to this repo here.

PS: Unfortunately, there is no setup.py file so I don't know how you upload it to Pypi, otherwise I could have provided a PR to do that.

**Comment by justin8** [comment]
Ah, thanks for that.

I changed from setup.py to use poetry a few weeks ago and didn't notice this. It seems I needed to specify the readme file, and then it maps that in to `long_description` for the `pkg-info`.

Fixed it here: https://github.com/justin8/convert_videos/pull/5
